### ISSUE TITLE
Characters Not Appearing

### ISSUE THREAD

**Issue by githubplanetarparrot** [TheTimeSweeper/the#17] opened 2023-11-18 19:52 UTC
As of the latest update the characters are simply not appearing in the character list, even if it is the only mod installed (plus dependencies).

**Comment by TheTimeSweeper** [comment] 2023-11-19 05:50
Please try to run the game and send me a log. In r2modman > settings > debugging > copy logoutput and paste it

**Comment by MikeVaz1** [comment] 2024-01-05 02:17
Same problem, with every second mod content is not appearing. what shuold i do if i dont have r2modman?

**Comment by TheTimeSweeper** [comment] 2024-01-05 08:07
What you do is get r2modman
If you can't cause you're sailing the seas, make sure you download every dependency of the mods you're downloading in the dependencies section in their thunderstore page, and make sure you get all the dependencies of those, and all the dependencies of those.

**Comment by TheTimeSweeper** [comment] 2024-01-25 08:42
closing as no more info had come so the problem is to be assumed solved

**Closed by TheTimeSweeper** 2024-01-25 08:42 UTC
